## Check Data Input

In [2]:
import pandas as pd

#### Google Reviews

In [7]:
google_df = pd.read_csv("../data_input/google_reviews.csv")

print(google_df.shape)
display(google_df.head(n=2))

(1100, 6)

,business_name,author_name,text,photo,rating,rating_category
0,Haci'nin Yeri - Yigit Lokantasi,Gulsum Akar,We went to Marmaris with my wife for a holiday...,dataset/taste/hacinin_yeri_gulsum_akar.png,5,taste
1,Haci'nin Yeri - Yigit Lokantasi,Oguzhan Cetin,During my holiday in Marmaris we ate here to f...,dataset/menu/hacinin_yeri_oguzhan_cetin.png,4,menu

#### Amazon Reviews

In [8]:
amazon_df = pd.read_csv("../data_input/amazon_reviews.csv", 
            names=['rating', 'reviewing_heading', 'review_text'])

print(amazon_df.shape)
display(amazon_df.head(n=2))

(400000, 3)

,rating,reviewing_heading,review_text
0,2,Great CD,My lovely Pat has one of the GREAT voices of h...
1,2,One of the best game music soundtracks - for a...,Despite the fact that I have only played a sma...