## Check Data Input

In [1]:
import pandas as pd

#### Google Reviews

In [2]:
google_df = pd.read_csv("../data_input/google_reviews.csv")

print(google_df.shape)
display(google_df.head(n=2))

(1100, 6)

,business_name,author_name,text,photo,rating,rating_category
0,Haci'nin Yeri - Yigit Lokantasi,Gulsum Akar,We went to Marmaris with my wife for a holiday...,dataset/taste/hacinin_yeri_gulsum_akar.png,5,taste
1,Haci'nin Yeri - Yigit Lokantasi,Oguzhan Cetin,During my holiday in Marmaris we ate here to f...,dataset/menu/hacinin_yeri_oguzhan_cetin.png,4,menu

In [4]:
print(google_df['business_name'].nunique())
print(google_df['author_name'].nunique())
print(google_df['rating_category'].value_counts())

100
1074
rating_category
taste                 330
indoor_atmosphere     288
outdoor_atmosphere    286
menu                  196
Name: count, dtype: int64

In [6]:
exp_df = google_df[google_df['business_name'] == "Haci'nin Yeri - Yigit Lokantasi"]
print(exp_df.shape)
display(exp_df)

(11, 6)

,business_name,author_name,text,photo,rating,rating_category
0,Haci'nin Yeri - Yigit Lokantasi,Gulsum Akar,We went to Marmaris with my wife for a holiday...,dataset/taste/hacinin_yeri_gulsum_akar.png,5,taste
1,Haci'nin Yeri - Yigit Lokantasi,Oguzhan Cetin,During my holiday in Marmaris we ate here to f...,dataset/menu/hacinin_yeri_oguzhan_cetin.png,4,menu
2,Haci'nin Yeri - Yigit Lokantasi,Yasin Kuyu,Prices are very affordable. The menu in the ph...,dataset/outdoor_atmosphere/hacinin_yeri_yasin_...,3,outdoor_atmosphere
3,Haci'nin Yeri - Yigit Lokantasi,Orhan Kapu,Turkey's cheapest artisan restaurant and its f...,dataset/indoor_atmosphere/hacinin_yeri_orhan_k...,5,indoor_atmosphere
4,Haci'nin Yeri - Yigit Lokantasi,Ozgur Sati,I don't know what you will look for in terms o...,dataset/menu/hacinin_yeri_ozgur_sati.png,3,menu
5,Haci'nin Yeri - Yigit Lokantasi,Arda Karaca,Generally good.,dataset/indoor_atmosphere/hacinin_yeri_arda_ka...,4,indoor_atmosphere
6,Haci'nin Yeri - Yigit Lokantasi,İrem Eren,What you see is 125 TL in total. It's a pretty...,dataset/taste/hacinin_yeri_irem_eren.png,5,taste
7,Haci'nin Yeri - Yigit Lokantasi,Nadia Salim,Delicious food at rock bottom prices. Friendly...,dataset/taste/hacinin_yeri_nadia_salim.png,5,taste
8,Haci'nin Yeri - Yigit Lokantasi,Mehmet Eser,"Every time I go, I still experience the amazem...",dataset/outdoor_atmosphere/hacinin_yeri_mehmet...,5,outdoor_atmosphere
9,Haci'nin Yeri - Yigit Lokantasi,Celal Ozer,The most f/p of all businesses I've seen.,dataset/indoor_atmosphere/hacinin_yeri_celal_o...,5,indoor_atmosphere
10,Haci'nin Yeri - Yigit Lokantasi,Onur Celebi,The food was just like the ones my mother made...,dataset/taste/hacinin_yeri_onur_celebi.png,5,taste

#### Amazon Reviews

In [8]:
amazon_df = pd.read_csv("../data_input/amazon_reviews.csv", 
            names=['rating', 'reviewing_heading', 'review_text'])

print(amazon_df.shape)
display(amazon_df.head(n=2))

(400000, 3)

,rating,reviewing_heading,review_text
0,2,Great CD,My lovely Pat has one of the GREAT voices of h...
1,2,One of the best game music soundtracks - for a...,Despite the fact that I have only played a sma...